import { HEALTHCARE_CATALOG_CHILDREN } from "./healthcareHierarchy";
import type { IndustryCatalogNode } from "./types";

const W = "warehouse" as const;
const L = "live-discovery" as const;
const P = "planned" as const;

/** Full industry catalog — presentation hierarchy with coverage and taxonomy mapping. */
export const INDUSTRY_CATALOG: IndustryCatalogNode[] = [
  {
    id: "healthcare",
    label: "Healthcare",
    description: "Payers, providers, and health services organizations",
    coverage: W,
    phase: 1,
    icon: "🏥",
    sectorId: "healthcare",
    children: HEALTHCARE_CATALOG_CHILDREN,
  },
  {
    id: "manufacturing",
    label: "Manufacturing",
    description: "Industrial, consumer, and life-sciences manufacturers",
    coverage: W,
    phase: 1,
    icon: "🏭",
    sectorId: "manufacturing",
    warehouseBuyerPack: "manufacturers",
    children: [
      {
        id: "pharmaceuticals",
        label: "Pharmaceuticals",
        description: "Drug makers, generics, and contract manufacturers",
        coverage: W,
        phase: 1,
        sectorId: "manufacturing",
        industryId: "pharma-manufacturing",
        organizationTypeId: "manufacturer",
        warehouseBuyerPack: "manufacturers",
      },
      {
        id: "medical-devices",
        label: "Medical Devices",
        description: "Device makers, diagnostics, and medtech",
        coverage: W,
        phase: 1,
        sectorId: "manufacturing",
        industryId: "medical-device-manufacturing",
        organizationTypeId: "manufacturer",
        warehouseBuyerPack: "manufacturers",
      },
      {
        id: "industrial",
        label: "Industrial",
        description: "Machinery, components, and industrial products",
        coverage: W,
        phase: 1,
        sectorId: "manufacturing",
        industryId: "industrial-products",
        organizationTypeId: "manufacturer",
        warehouseBuyerPack: "manufacturers",
      },
      {
        id: "automotive",
        label: "Automotive",
        description: "OEMs, parts suppliers, and vehicle assembly",
        coverage: W,
        phase: 1,
        sectorId: "manufacturing",
        industryId: "automotive",
        organizationTypeId: "automotive-manufacturer",
        warehouseBuyerPack: "manufacturers",
      },
      {
        id: "aerospace",
        label: "Aerospace",
        description: "Aircraft, defense, and space manufacturing",
        coverage: L,
        phase: 3,
        sectorId: "manufacturing",
        industryId: "industrial-products",
        organizationTypeId: "manufacturer",
      },
      {
        id: "food-beverage",
        label: "Food & Beverage",
        description: "CPG food, beverage, and packaged goods",
        coverage: W,
        phase: 1,
        sectorId: "manufacturing",
        industryId: "food-beverage",
        organizationTypeId: "food-beverage-company",
        warehouseBuyerPack: "manufacturers",
      },
      {
        id: "electronics",
        label: "Electronics",
        description: "Semiconductors, components, and consumer electronics",
        coverage: L,
        phase: 3,
        sectorId: "manufacturing",
        industryId: "industrial-products",
        organizationTypeId: "manufacturer",
      },
    ],
  },
  {
    id: "higher-education",
    label: "Higher Education",
    description: "Colleges, universities, and research institutions",
    coverage: L,
    phase: 3,
    icon: "🎓",
    sectorId: "education",
    children: [
      {
        id: "universities",
        label: "Universities",
        description: "Four-year and research universities",
        coverage: L,
        phase: 3,
        sectorId: "education",
        industryId: "universities",
        organizationTypeId: "university",
      },
      {
        id: "community-colleges",
        label: "Community Colleges",
        description: "Two-year and technical colleges",
        coverage: L,
        phase: 3,
        sectorId: "education",
        industryId: "community-colleges",
        organizationTypeId: "community-college",
      },
      {
        id: "private-colleges",
        label: "Private Colleges",
        description: "Private four-year institutions",
        coverage: L,
        phase: 3,
        sectorId: "education",
        industryId: "private-schools",
        organizationTypeId: "private-school",
      },
      {
        id: "research-institutions",
        label: "Research Institutions",
        description: "R1 universities and research centers",
        coverage: L,
        phase: 3,
        sectorId: "education",
        industryId: "universities",
        organizationTypeId: "university",
      },
    ],
  },
  {
    id: "financial-services",
    label: "Financial Services",
    description: "Banks, insurers, asset managers, and fintech",
    coverage: L,
    phase: 3,
    icon: "🏦",
    sectorId: "financial-services",
    children: [
      {
        id: "banks",
        label: "Banks",
        description: "National and regional banks",
        coverage: L,
        phase: 3,
        sectorId: "financial-services",
        industryId: "banks",
        organizationTypeId: "bank",
      },
      {
        id: "credit-unions",
        label: "Credit Unions",
        description: "Member-owned financial cooperatives",
        coverage: L,
        phase: 3,
        sectorId: "financial-services",
        industryId: "credit-unions",
        organizationTypeId: "credit-union",
      },
      {
        id: "insurance-carriers",
        label: "Insurance Carriers",
        description: "P&C, life, and specialty insurers",
        coverage: L,
        phase: 3,
        sectorId: "financial-services",
        industryId: "insurance-carriers",
        organizationTypeId: "insurance-carrier",
      },
      {
        id: "asset-managers",
        label: "Asset Managers",
        description: "Investment and fund managers",
        coverage: L,
        phase: 3,
        sectorId: "financial-services",
        industryId: "asset-managers",
        organizationTypeId: "asset-manager",
      },
      {
        id: "fintech",
        label: "Fintech",
        description: "Payments, neobanks, and financial platforms",
        coverage: L,
        phase: 3,
        sectorId: "financial-services",
        industryId: "fintech",
        organizationTypeId: "fintech-company",
      },
    ],
  },
  {
    id: "technology",
    label: "Technology",
    description: "Software, SaaS, and technology platforms",
    coverage: L,
    phase: 3,
    icon: "💻",
    sectorId: "technology",
    industryId: "technology",
    children: [
      {
        id: "software-saas",
        label: "Software & SaaS",
        description: "Enterprise software and cloud platforms",
        coverage: L,
        phase: 3,
        sectorId: "technology",
        industryId: "technology",
        organizationTypeId: "employer",
      },
      {
        id: "hardware-semiconductor",
        label: "Hardware & Semiconductor",
        description: "Chip makers and hardware OEMs",
        coverage: L,
        phase: 4,
        sectorId: "technology",
      },
      {
        id: "it-services",
        label: "IT Services",
        description: "Systems integrators and managed services",
        coverage: L,
        phase: 4,
        sectorId: "technology",
      },
    ],
  },
  {
    id: "retail-consumer",
    label: "Retail & Consumer",
    description: "Retail chains, consumer brands, and e-commerce",
    coverage: L,
    phase: 3,
    icon: "🛒",
    sectorId: "retail-consumer",
    industryId: "retail",
    children: [
      {
        id: "retail-chains",
        label: "Retail Chains",
        description: "National and regional retailers",
        coverage: L,
        phase: 3,
        sectorId: "retail-consumer",
        industryId: "retail",
        organizationTypeId: "employer",
      },
      {
        id: "consumer-brands",
        label: "Consumer Brands",
        description: "DTC and omnichannel brands",
        coverage: L,
        phase: 3,
        sectorId: "retail-consumer",
        industryId: "retail",
      },
      {
        id: "grocery",
        label: "Grocery",
        description: "Supermarkets and grocery chains",
        coverage: L,
        phase: 3,
        sectorId: "retail-consumer",
        industryId: "retail",
      },
    ],
  },
  {
    id: "government",
    label: "Government",
    description: "Federal, state, and local public sector",
    coverage: L,
    phase: 3,
    icon: "🏛️",
    sectorId: "public-sector",
    children: [
      {
        id: "state-agencies",
        label: "State Agencies",
        description: "State departments and agencies",
        coverage: L,
        phase: 3,
        sectorId: "public-sector",
        industryId: "state-agencies",
        organizationTypeId: "state-agency",
      },
      {
        id: "municipalities",
        label: "Municipalities",
        description: "Cities, counties, and local government",
        coverage: L,
        phase: 3,
        sectorId: "public-sector",
        industryId: "municipalities",
        organizationTypeId: "municipality",
      },
      {
        id: "transit-authorities",
        label: "Transit Authorities",
        description: "Public transit and transportation agencies",
        coverage: L,
        phase: 3,
        sectorId: "public-sector",
        industryId: "transit-authorities",
        organizationTypeId: "transit-authority",
      },
      {
        id: "school-districts",
        label: "School Districts",
        description: "K-12 public school districts",
        coverage: L,
        phase: 3,
        sectorId: "education",
        industryId: "school-districts",
        organizationTypeId: "school-district",
      },
    ],
  },
  {
    id: "life-sciences",
    label: "Life Sciences",
    description: "Pharma, biotech, diagnostics, and research",
    coverage: L,
    phase: 2,
    icon: "🧬",
    sectorId: "healthcare",
    industryId: "life-sciences",
    children: [
      {
        id: "ls-pharma",
        label: "Pharmaceuticals",
        description: "Drug discovery and pharmaceutical companies",
        coverage: W,
        phase: 1,
        sectorId: "healthcare",
        industryId: "life-sciences",
        organizationTypeId: "pharma-manufacturer",
        warehouseBuyerPack: "manufacturers",
      },
      {
        id: "ls-biotech",
        label: "Biotechnology",
        description: "Biotech and gene therapy companies",
        coverage: L,
        phase: 2,
        sectorId: "healthcare",
        industryId: "life-sciences",
        organizationTypeId: "pharma-manufacturer",
      },
      {
        id: "ls-diagnostics",
        label: "Diagnostics",
        description: "Diagnostic labs and testing companies",
        coverage: L,
        phase: 2,
        sectorId: "healthcare",
        industryId: "life-sciences",
        organizationTypeId: "medical-device",
      },
      {
        id: "ls-digital-therapeutics",
        label: "Digital Therapeutics",
        description: "Software-based therapeutic interventions",
        coverage: P,
        phase: 2,
        sectorId: "healthcare",
      },
    ],
  },
  {
    id: "energy",
    label: "Energy",
    description: "Oil, gas, renewables, and power generation",
    coverage: L,
    phase: 4,
    icon: "⚡",
    sectorId: "energy-utilities",
    industryId: "energy",
    children: [
      {
        id: "oil-gas",
        label: "Oil & Gas",
        description: "Exploration, production, and refining",
        coverage: L,
        phase: 4,
        sectorId: "energy-utilities",
        industryId: "energy",
      },
      {
        id: "renewables",
        label: "Renewables",
        description: "Solar, wind, and clean energy",
        coverage: L,
        phase: 4,
        sectorId: "energy-utilities",
        industryId: "energy",
      },
      {
        id: "utilities",
        label: "Utilities",
        description: "Electric, gas, and water utilities",
        coverage: L,
        phase: 4,
        sectorId: "energy-utilities",
        industryId: "utilities",
      },
    ],
  },
  {
    id: "transportation",
    label: "Transportation",
    description: "Airlines, freight, logistics, and rail",
    coverage: L,
    phase: 4,
    icon: "🚚",
    sectorId: "transportation-logistics",
    industryId: "transportation",
    children: [
      {
        id: "logistics-freight",
        label: "Logistics & Freight",
        description: "3PL, trucking, and freight forwarders",
        coverage: L,
        phase: 4,
        sectorId: "transportation-logistics",
        industryId: "transportation",
      },
      {
        id: "airlines",
        label: "Airlines",
        description: "Commercial aviation carriers",
        coverage: L,
        phase: 4,
        sectorId: "transportation-logistics",
      },
      {
        id: "rail",
        label: "Rail",
        description: "Freight and passenger rail operators",
        coverage: L,
        phase: 4,
        sectorId: "transportation-logistics",
      },
    ],
  },
  {
    id: "nonprofits",
    label: "Nonprofits",
    description: "Foundations, charities, and NGOs",
    coverage: L,
    phase: 3,
    icon: "💚",
    sectorId: "nonprofit",
    industryId: "nonprofit",
    organizationTypeId: "nonprofit",
    children: [
      {
        id: "foundations",
        label: "Foundations",
        description: "Private and community foundations",
        coverage: L,
        phase: 3,
        sectorId: "nonprofit",
        industryId: "nonprofit",
        organizationTypeId: "nonprofit",
      },
      {
        id: "charities",
        label: "Charities",
        description: "Human services and advocacy organizations",
        coverage: L,
        phase: 3,
        sectorId: "nonprofit",
        industryId: "nonprofit",
        organizationTypeId: "nonprofit",
      },
      {
        id: "healthcare-nonprofits",
        label: "Healthcare Nonprofits",
        description: "Hospital systems and health charities",
        coverage: L,
        phase: 3,
        sectorId: "nonprofit",
      },
    ],
  },
  {
    id: "professional-services",
    label: "Professional Services",
    description: "Consulting, legal, accounting, and staffing",
    coverage: L,
    phase: 4,
    icon: "📊",
    sectorId: "professional-services",
    children: [
      {
        id: "consulting",
        label: "Consulting",
        description: "Management and strategy consulting",
        coverage: L,
        phase: 4,
        sectorId: "professional-services",
        industryId: "consulting",
        organizationTypeId: "consulting-firm",
      },
      {
        id: "legal",
        label: "Legal",
        description: "Law firms and legal services",
        coverage: L,
        phase: 4,
        sectorId: "professional-services",
        industryId: "legal",
        organizationTypeId: "law-firm",
      },
      {
        id: "accounting",
        label: "Accounting",
        description: "CPA firms and audit practices",
        coverage: L,
        phase: 4,
        sectorId: "professional-services",
        industryId: "accounting",
        organizationTypeId: "accounting-firm",
      },
      {
        id: "staffing",
        label: "Staffing",
        description: "Recruiting and temp staffing firms",
        coverage: L,
        phase: 4,
        sectorId: "professional-services",
        industryId: "staffing",
        organizationTypeId: "staffing-firm",
      },
    ],
  },
  {
    id: "real-estate",
    label: "Real Estate",
    description: "Developers, REITs, and property managers",
    coverage: L,
    phase: 4,
    icon: "🏢",
    sectorId: "real-estate-construction",
    industryId: "real-estate",
    children: [
      {
        id: "developers",
        label: "Developers",
        description: "Commercial and residential developers",
        coverage: L,
        phase: 4,
        sectorId: "real-estate-construction",
        industryId: "real-estate",
      },
      {
        id: "reits",
        label: "REITs",
        description: "Real estate investment trusts",
        coverage: L,
        phase: 4,
        sectorId: "real-estate-construction",
        industryId: "real-estate",
      },
      {
        id: "property-management",
        label: "Property Management",
        description: "Property managers and operators",
        coverage: L,
        phase: 4,
        sectorId: "real-estate-construction",
        industryId: "real-estate",
      },
    ],
  },
  {
    id: "hospitality",
    label: "Hospitality",
    description: "Hotels, restaurants, and travel",
    coverage: L,
    phase: 4,
    icon: "🏨",
    sectorId: "hospitality-leisure",
    industryId: "hospitality",
    children: [
      {
        id: "hotels",
        label: "Hotels",
        description: "Hotel chains and lodging operators",
        coverage: L,
        phase: 4,
        sectorId: "hospitality-leisure",
        industryId: "hospitality",
      },
      {
        id: "restaurants",
        label: "Restaurants",
        description: "Restaurant groups and QSR chains",
        coverage: L,
        phase: 4,
        sectorId: "hospitality-leisure",
        industryId: "hospitality",
      },
      {
        id: "travel",
        label: "Travel",
        description: "OTAs, cruise lines, and travel platforms",
        coverage: L,
        phase: 4,
        sectorId: "hospitality-leisure",
      },
    ],
  },
  {
    id: "media-entertainment",
    label: "Media & Entertainment",
    description: "Studios, streaming, publishing, and gaming",
    coverage: P,
    phase: 4,
    icon: "🎬",
    children: [
      {
        id: "streaming",
        label: "Streaming",
        description: "Streaming platforms and digital media",
        coverage: P,
        phase: 4,
      },
      {
        id: "publishing",
        label: "Publishing",
        description: "Publishers and media companies",
        coverage: P,
        phase: 4,
      },
      {
        id: "gaming",
        label: "Gaming",
        description: "Game studios and interactive entertainment",
        coverage: P,
        phase: 4,
      },
    ],
  },
  {
    id: "telecommunications",
    label: "Telecommunications",
    description: "Carriers, ISPs, and network infrastructure",
    coverage: P,
    phase: 4,
    icon: "📡",
    children: [
      {
        id: "carriers",
        label: "Carriers",
        description: "Wireless and wireline carriers",
        coverage: P,
        phase: 4,
      },
      {
        id: "isps",
        label: "ISPs",
        description: "Internet service providers",
        coverage: P,
        phase: 4,
      },
      {
        id: "network-infrastructure",
        label: "Network Infrastructure",
        description: "Tower cos and fiber operators",
        coverage: P,
        phase: 4,
      },
    ],
  },
  {
    id: "agriculture",
    label: "Agriculture",
    description: "Agribusiness, farming, and food production",
    coverage: P,
    phase: 4,
    icon: "🌾",
    children: [
      {
        id: "agribusiness",
        label: "Agribusiness",
        description: "Large-scale agricultural operations",
        coverage: P,
        phase: 4,
      },
      {
        id: "food-production",
        label: "Food Production",
        description: "Agricultural food processors",
        coverage: L,
        phase: 4,
        sectorId: "manufacturing",
        industryId: "food-beverage",
        organizationTypeId: "food-beverage-company",
      },
    ],
  },
  {
    id: "construction",
    label: "Construction",
    description: "General contractors, engineering, and infrastructure",
    coverage: L,
    phase: 4,
    icon: "🏗️",
    sectorId: "real-estate-construction",
    industryId: "construction",
    children: [
      {
        id: "general-contractors",
        label: "General Contractors",
        description: "Commercial and residential GCs",
        coverage: L,
        phase: 4,
        sectorId: "real-estate-construction",
        industryId: "construction",
      },
      {
        id: "engineering",
        label: "Engineering",
        description: "Civil and structural engineering firms",
        coverage: L,
        phase: 4,
        sectorId: "real-estate-construction",
        industryId: "construction",
      },
      {
        id: "infrastructure",
        label: "Infrastructure",
        description: "Heavy civil and infrastructure builders",
        coverage: L,
        phase: 4,
        sectorId: "real-estate-construction",
        industryId: "construction",
      },
    ],
  },
];

export function buildCatalogIndex(
  nodes: IndustryCatalogNode[] = INDUSTRY_CATALOG,
): Map<string, IndustryCatalogNode> {
  const map = new Map<string, IndustryCatalogNode>();
  function walk(list: IndustryCatalogNode[]) {
    for (const node of list) {
      map.set(node.id, node);
      if (node.children) walk(node.children);
    }
  }
  walk(nodes);
  return map;
}

export const CATALOG_INDEX = buildCatalogIndex();

export function getCatalogNode(id: string): IndustryCatalogNode | undefined {
  return CATALOG_INDEX.get(id);
}

export function topLevelCatalogNodes(): IndustryCatalogNode[] {
  return INDUSTRY_CATALOG;
}
