import type { OrganizationRecord } from "./types";

export const EDUCATION_DIRECTORY: OrganizationRecord[] = [
  {
    id: "dir-edu-osu",
    name: "The Ohio State University",
    aliases: ["ohio state", "osu", "ohio state university"],
    organizationType: "university",
    sectorId: "education",
    industryId: "universities",
    organizationTypeId: "university",
    industry: "universities",
    website: "https://www.osu.edu",
    headquarters: "Columbus, OH",
    statesServed: ["OH"],
    regions: ["midwest"],
    employeeEstimate: 35_000,
    tags: ["university", "ohio"],
    knownSignals: [],
    relevantProviders: ["company-site", "news-rss"],
    buyerPack: "employers",
  },
  {
    id: "dir-edu-pitt",
    name: "University of Pittsburgh",
    aliases: ["pitt", "university of pittsburgh"],
    organizationType: "university",
    sectorId: "education",
    industryId: "universities",
    organizationTypeId: "university",
    industry: "universities",
    website: "https://www.pitt.edu",
    headquarters: "Pittsburgh, PA",
    statesServed: ["PA"],
    regions: ["mid-atlantic", "northeast"],
    employeeEstimate: 14_000,
    tags: ["university", "pennsylvania"],
    knownSignals: [],
    relevantProviders: ["company-site", "news-rss"],
    buyerPack: "employers",
  },
  {
    id: "dir-edu-penn",
    name: "University of Pennsylvania",
    aliases: ["upenn", "penn", "university of pennsylvania"],
    organizationType: "university",
    sectorId: "education",
    industryId: "universities",
    organizationTypeId: "university",
    industry: "universities",
    website: "https://www.upenn.edu",
    headquarters: "Philadelphia, PA",
    statesServed: ["PA"],
    regions: ["mid-atlantic", "northeast"],
    employeeEstimate: 22_000,
    tags: ["university", "pennsylvania", "ivy"],
    knownSignals: [],
    relevantProviders: ["company-site", "news-rss"],
    buyerPack: "employers",
  },
];
