import type { OrganizationRecord } from "./types";

export const FINANCIAL_SERVICES_DIRECTORY: OrganizationRecord[] = [
  {
    id: "dir-fin-pnc",
    name: "PNC Financial Services",
    aliases: ["pnc bank", "pnc"],
    organizationType: "employer",
    sectorId: "financial-services",
    industryId: "banks",
    organizationTypeId: "bank",
    industry: "banks",
    website: "https://www.pnc.com",
    headquarters: "Pittsburgh, PA",
    statesServed: ["PA", "OH", "NJ", "MD", "MI"],
    regions: ["mid-atlantic", "midwest", "northeast"],
    employeeEstimate: 55_000,
    publicCompany: true,
    ticker: "PNC",
    tags: ["bank", "regional bank"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
    buyerPack: "employers",
  },
  {
    id: "dir-fin-huntington",
    name: "Huntington Bancshares",
    aliases: ["huntington bank", "huntington"],
    organizationType: "employer",
    sectorId: "financial-services",
    industryId: "banks",
    organizationTypeId: "bank",
    industry: "banks",
    website: "https://www.huntington.com",
    headquarters: "Columbus, OH",
    statesServed: ["OH", "MI", "PA", "IN", "KY"],
    regions: ["midwest"],
    employeeEstimate: 20_000,
    publicCompany: true,
    ticker: "HBAN",
    tags: ["bank", "regional bank", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
    buyerPack: "employers",
  },
  {
    id: "dir-fin-keybank",
    name: "KeyCorp",
    aliases: ["key bank", "keycorp"],
    organizationType: "employer",
    sectorId: "financial-services",
    industryId: "banks",
    organizationTypeId: "bank",
    industry: "banks",
    website: "https://www.key.com",
    headquarters: "Cleveland, OH",
    statesServed: ["OH", "PA", "NY", "MI"],
    regions: ["midwest", "northeast"],
    employeeEstimate: 17_000,
    publicCompany: true,
    ticker: "KEY",
    tags: ["bank", "regional bank", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
    buyerPack: "employers",
  },
  {
    id: "dir-fin-fifth-third",
    name: "Fifth Third Bancorp",
    aliases: ["fifth third bank", "fifth third"],
    organizationType: "employer",
    sectorId: "financial-services",
    industryId: "banks",
    organizationTypeId: "bank",
    industry: "banks",
    website: "https://www.53.com",
    headquarters: "Cincinnati, OH",
    statesServed: ["OH", "KY", "IN", "MI", "FL"],
    regions: ["midwest", "southeast"],
    employeeEstimate: 19_000,
    publicCompany: true,
    ticker: "FITB",
    tags: ["bank", "regional bank", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
    buyerPack: "employers",
  },
];
