import type { OrganizationRecord } from "./types";

/**
 * Curated health plan directory — source of truth for plan existence.
 * National carriers plus Pennsylvania regional plans (minimum coverage).
 */
export const HEALTH_PLANS_DIRECTORY: OrganizationRecord[] = [
  // ---------------------------------------------------------------------------
  // National plans
  // ---------------------------------------------------------------------------
  {
    id: "dir-hp-uhc",
    name: "UnitedHealthcare",
    aliases: [
      "united healthcare",
      "uhc",
      "unitedhealth",
      "united health group",
      "unitedhealthcare medicare",
    ],
    parentOrganization: "UnitedHealth Group",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.uhc.com",
    headquarters: "Minnetonka, MN",
    statesServed: ["PA", "FL", "TX", "CA", "NY", "AZ", "OH", "MN", "NJ", "IL"],
    regions: ["national", "mid-atlantic", "northeast", "southeast", "midwest", "southwest", "west"],
    memberEstimate: 50_000_000,
    commercial: true,
    medicare: true,
    medicaid: true,
    exchange: true,
    aso: true,
    tpa: true,
    publicCompany: true,
    ticker: "UNH",
    cmsContracts: ["H0028", "H0322", "H0271"],
    tags: ["national", "national-carrier"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-aetna",
    name: "Aetna",
    aliases: ["aetna medicare", "cvs aetna", "aetna health"],
    parentOrganization: "CVS Health",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.aetna.com",
    headquarters: "Hartford, CT",
    statesServed: ["PA", "CT", "FL", "TX", "OH", "CA", "NY", "NJ"],
    regions: ["national", "mid-atlantic", "northeast", "southeast", "midwest", "west"],
    memberEstimate: 22_000_000,
    commercial: true,
    medicare: true,
    medicaid: false,
    exchange: true,
    aso: true,
    publicCompany: true,
    ticker: "CVS",
    cmsContracts: ["H5521", "H1609"],
    tags: ["national", "national-carrier"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-cigna",
    name: "Cigna Healthcare",
    aliases: ["cigna", "healthspring", "cigna group"],
    parentOrganization: "The Cigna Group",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.cigna.com",
    headquarters: "Bloomfield, CT",
    statesServed: ["PA", "AZ", "FL", "TX", "TN", "CO", "NJ"],
    regions: ["national", "mid-atlantic", "northeast", "southeast", "southwest"],
    memberEstimate: 18_000_000,
    commercial: true,
    medicare: true,
    medicaid: false,
    exchange: true,
    aso: true,
    publicCompany: true,
    ticker: "CI",
    cmsContracts: ["H0544", "H4513"],
    tags: ["national", "national-carrier"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-humana",
    name: "Humana",
    aliases: ["humana inc", "humana medicare", "humana health"],
    parentOrganization: "Humana Inc.",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.humana.com",
    headquarters: "Louisville, KY",
    statesServed: ["PA", "FL", "KY", "TX", "OH", "GA", "IL"],
    regions: ["national", "mid-atlantic", "southeast", "midwest", "southwest"],
    memberEstimate: 17_000_000,
    commercial: true,
    medicare: true,
    medicaid: true,
    exchange: true,
    publicCompany: true,
    ticker: "HUM",
    cmsContracts: ["H5216", "H0434"],
    tags: ["national", "national-carrier"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-elevance",
    name: "Elevance Health",
    aliases: [
      "elevance",
      "anthem",
      "anthem blue cross",
      "wellpoint",
      "anthem bcbs",
    ],
    parentOrganization: "Elevance Health, Inc.",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.elevancehealth.com",
    headquarters: "Indianapolis, IN",
    statesServed: ["PA", "IN", "OH", "GA", "CA", "NY", "TX", "KY", "WI", "MO"],
    regions: ["national", "mid-atlantic", "midwest", "southeast", "northeast", "west"],
    memberEstimate: 47_000_000,
    commercial: true,
    medicare: true,
    medicaid: true,
    exchange: true,
    aso: true,
    publicCompany: true,
    ticker: "ELV",
    cmsContracts: ["H0537", "H0597"],
    tags: ["national", "national-carrier", "blues"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-kaiser",
    name: "Kaiser Permanente",
    aliases: ["kaiser", "kaiser foundation health plan", "kp", "kaiser permanente health plan"],
    parentOrganization: "Kaiser Foundation Health Plan, Inc.",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.kp.org",
    headquarters: "Oakland, CA",
    statesServed: ["CA", "OR", "WA", "CO", "GA", "MD", "VA", "HI"],
    regions: ["west", "national"],
    memberEstimate: 12_700_000,
    commercial: true,
    medicare: true,
    medicaid: true,
    exchange: true,
    publicCompany: false,
    cmsContracts: ["H0169", "H0522"],
    tags: ["national", "national-carrier", "integrated-delivery"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-centene",
    name: "Centene",
    aliases: ["centene corporation", "wellcare", "centene health"],
    parentOrganization: "Centene Corporation",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.centene.com",
    headquarters: "St. Louis, MO",
    statesServed: ["PA", "MO", "FL", "TX", "CA", "AZ", "GA", "OH", "MI"],
    regions: ["national", "mid-atlantic", "midwest", "southeast", "southwest", "west"],
    memberEstimate: 28_000_000,
    commercial: true,
    medicare: true,
    medicaid: true,
    exchange: true,
    publicCompany: true,
    ticker: "CNC",
    cmsContracts: ["H0885", "H2166"],
    tags: ["national", "national-carrier", "managed-medicaid"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-molina",
    name: "Molina Healthcare",
    aliases: ["molina", "molina health"],
    parentOrganization: "Molina Healthcare, Inc.",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.molinahealthcare.com",
    headquarters: "Long Beach, CA",
    statesServed: ["PA", "CA", "TX", "MI", "OH", "FL", "WA", "WI"],
    regions: ["national", "mid-atlantic", "midwest", "southeast", "southwest", "west"],
    memberEstimate: 5_000_000,
    commercial: false,
    medicare: true,
    medicaid: true,
    exchange: true,
    publicCompany: true,
    ticker: "MOH",
    cmsContracts: ["H5629", "H1790"],
    tags: ["national", "national-carrier", "managed-medicaid"],
    buyerPack: "health-plans",
  },

  // ---------------------------------------------------------------------------
  // Pennsylvania regional plans
  // ---------------------------------------------------------------------------
  {
    id: "dir-hp-ibx",
    name: "Independence Blue Cross",
    aliases: ["ibx", "independence health", "independence bcbs", "independence blue cross pa"],
    parentOrganization: "Independence Health Group",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.ibx.com",
    headquarters: "Philadelphia, PA",
    statesServed: ["PA", "NJ"],
    regions: ["mid-atlantic", "northeast"],
    memberEstimate: 2_500_000,
    commercial: true,
    medicare: true,
    medicaid: false,
    exchange: true,
    aso: true,
    publicCompany: false,
    cmsContracts: ["H5594", "H2159"],
    tags: ["blues", "pennsylvania", "regional"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-highmark",
    name: "Highmark",
    aliases: [
      "highmark inc",
      "highmark health",
      "bcbs pa",
      "blue cross pennsylvania",
      "blue cross blue shield pennsylvania",
      "highmark blue cross blue shield",
    ],
    parentOrganization: "Highmark Health",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.highmark.com",
    headquarters: "Pittsburgh, PA",
    statesServed: ["PA", "WV", "DE", "NY"],
    regions: ["mid-atlantic", "northeast"],
    memberEstimate: 6_800_000,
    commercial: true,
    medicare: true,
    medicaid: true,
    exchange: true,
    aso: true,
    publicCompany: false,
    cmsContracts: ["H3015", "H4032", "H5597"],
    tags: ["blues", "pennsylvania", "regional"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-capital-bc",
    name: "Capital Blue Cross",
    aliases: ["capital bc", "capital blue", "capital bluecross", "cbc"],
    parentOrganization: "Capital Blue Cross",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.capbluecross.com",
    headquarters: "Harrisburg, PA",
    statesServed: ["PA"],
    regions: ["mid-atlantic", "northeast"],
    memberEstimate: 1_200_000,
    commercial: true,
    medicare: true,
    medicaid: false,
    exchange: true,
    aso: true,
    publicCompany: false,
    tags: ["blues", "pennsylvania", "regional"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-geisinger-hp",
    name: "Geisinger Health Plan",
    aliases: ["geisinger plan", "geisinger insurance", "ghp"],
    parentOrganization: "Geisinger",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.geisinger.org/health-plan",
    headquarters: "Danville, PA",
    statesServed: ["PA"],
    regions: ["mid-atlantic", "northeast"],
    memberEstimate: 600_000,
    commercial: true,
    medicare: true,
    medicaid: true,
    exchange: true,
    publicCompany: false,
    tags: ["pennsylvania", "regional", "provider-sponsored"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-upmc-hp",
    name: "UPMC Health Plan",
    aliases: ["upmc insurance", "upmc health insurance", "upmc plan"],
    parentOrganization: "UPMC",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.upmchealthplan.com",
    headquarters: "Pittsburgh, PA",
    statesServed: ["PA", "OH", "WV"],
    regions: ["mid-atlantic", "northeast", "midwest"],
    memberEstimate: 900_000,
    commercial: true,
    medicare: true,
    medicaid: true,
    exchange: true,
    aso: true,
    publicCompany: false,
    tags: ["pennsylvania", "regional", "provider-sponsored"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-amerihealth-caritas-pa",
    name: "AmeriHealth Caritas Pennsylvania",
    aliases: ["amerihealth caritas pa", "amerihealth caritas", "caritas pa"],
    parentOrganization: "Independence Health Group",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.amerihealthcaritaspa.com",
    headquarters: "Philadelphia, PA",
    statesServed: ["PA"],
    regions: ["mid-atlantic", "northeast"],
    memberEstimate: 350_000,
    commercial: false,
    medicare: false,
    medicaid: true,
    exchange: false,
    publicCompany: false,
    tags: ["pennsylvania", "regional", "managed-medicaid"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-health-partners-plans",
    name: "Health Partners Plans",
    aliases: ["hpp", "health partners plan", "healthpartners plans"],
    parentOrganization: "Health Partners Plans",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.healthpartnersplans.com",
    headquarters: "Philadelphia, PA",
    statesServed: ["PA"],
    regions: ["mid-atlantic", "northeast"],
    memberEstimate: 280_000,
    commercial: false,
    medicare: true,
    medicaid: true,
    exchange: false,
    publicCompany: false,
    tags: ["pennsylvania", "regional", "managed-medicaid"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-keystone-first",
    name: "Keystone First",
    aliases: ["keystone first choice", "keystone medicaid"],
    parentOrganization: "Centene Corporation",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.keystonefirstpa.com",
    headquarters: "Harrisburg, PA",
    statesServed: ["PA"],
    regions: ["mid-atlantic", "northeast"],
    memberEstimate: 400_000,
    commercial: false,
    medicare: false,
    medicaid: true,
    exchange: false,
    publicCompany: false,
    tags: ["pennsylvania", "regional", "managed-medicaid"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-pa-health-wellness",
    name: "Pennsylvania Health & Wellness",
    aliases: ["pa health and wellness", "pennsylvania health and wellness", "phw"],
    parentOrganization: "Centene Corporation",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.pahealthwellness.com",
    headquarters: "Harrisburg, PA",
    statesServed: ["PA"],
    regions: ["mid-atlantic", "northeast"],
    memberEstimate: 200_000,
    commercial: false,
    medicare: true,
    medicaid: true,
    exchange: false,
    publicCompany: false,
    tags: ["pennsylvania", "regional", "managed-medicaid"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-upmc-for-life",
    name: "UPMC for Life",
    aliases: ["upmc for life medicare", "upmc medicare", "upmc ma"],
    parentOrganization: "UPMC",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.upmchealthplan.com/medicare",
    headquarters: "Pittsburgh, PA",
    statesServed: ["PA", "OH", "WV"],
    regions: ["mid-atlantic", "northeast", "midwest"],
    memberEstimate: 250_000,
    commercial: false,
    medicare: true,
    medicaid: false,
    exchange: false,
    publicCompany: false,
    cmsContracts: ["H2802"],
    tags: ["pennsylvania", "regional", "medicare-advantage"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-geisinger-gold",
    name: "Geisinger Gold",
    aliases: ["geisinger gold medicare", "geisinger ma", "geisinger medicare advantage"],
    parentOrganization: "Geisinger",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.geisinger.org/health-plan/medicare",
    headquarters: "Danville, PA",
    statesServed: ["PA"],
    regions: ["mid-atlantic", "northeast"],
    memberEstimate: 120_000,
    commercial: false,
    medicare: true,
    medicaid: false,
    exchange: false,
    publicCompany: false,
    tags: ["pennsylvania", "regional", "medicare-advantage"],
    buyerPack: "health-plans",
  },

  // ---------------------------------------------------------------------------
  // Midwest Blues (directory coverage for regional search)
  // ---------------------------------------------------------------------------
  {
    id: "dir-hp-bcbs-mi",
    name: "Blue Cross Blue Shield of Michigan",
    aliases: ["bcbs michigan", "bcbsmi", "blue cross michigan", "bcbs of michigan"],
    parentOrganization: "Blue Cross Blue Shield of Michigan Mutual Insurance Company",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.bcbsm.com",
    headquarters: "Detroit, MI",
    statesServed: ["MI"],
    regions: ["midwest", "great-lakes"],
    memberEstimate: 4_600_000,
    commercial: true,
    medicare: true,
    medicaid: true,
    exchange: true,
    aso: true,
    publicCompany: false,
    cmsContracts: ["H0294"],
    tags: ["blues", "midwest", "regional"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-bcbs-il",
    name: "Blue Cross Blue Shield of Illinois",
    aliases: ["bcbs illinois", "bcbsil", "hcsc", "blue cross illinois"],
    parentOrganization: "Health Care Service Corporation",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.bcbsil.com",
    headquarters: "Chicago, IL",
    statesServed: ["IL", "TX", "OK", "MT", "NM"],
    regions: ["midwest", "southwest"],
    memberEstimate: 8_500_000,
    commercial: true,
    medicare: true,
    medicaid: false,
    exchange: true,
    aso: true,
    publicCompany: false,
    cmsContracts: ["H0154"],
    tags: ["blues", "midwest", "regional"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-bcbs-mn",
    name: "Blue Cross Blue Shield of Minnesota",
    aliases: ["bcbs minnesota", "bcbsmn", "blue cross minnesota"],
    parentOrganization: "Blue Cross and Blue Shield of Minnesota",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.bluecrossmn.com",
    headquarters: "Eagan, MN",
    statesServed: ["MN"],
    regions: ["midwest", "upper-midwest"],
    memberEstimate: 2_800_000,
    commercial: true,
    medicare: true,
    medicaid: true,
    exchange: true,
    aso: true,
    publicCompany: false,
    tags: ["blues", "midwest", "regional"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-bcbs-wi",
    name: "Anthem Blue Cross Blue Shield Wisconsin",
    aliases: ["bcbs wisconsin", "anthem wisconsin", "blue cross wisconsin"],
    parentOrganization: "Elevance Health",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.anthem.com/wisconsin",
    headquarters: "Madison, WI",
    statesServed: ["WI"],
    regions: ["midwest", "great-lakes"],
    memberEstimate: 1_500_000,
    commercial: true,
    medicare: true,
    medicaid: false,
    exchange: true,
    publicCompany: false,
    tags: ["blues", "midwest", "regional"],
    buyerPack: "health-plans",
  },
  {
    id: "dir-hp-bcbs-oh",
    name: "Anthem Blue Cross Blue Shield Ohio",
    aliases: ["bcbs ohio", "anthem ohio", "blue cross ohio"],
    parentOrganization: "Elevance Health",
    organizationType: "health-plan",
    industry: "health-plans",
    website: "https://www.anthem.com/ohio",
    headquarters: "Cleveland, OH",
    statesServed: ["OH"],
    regions: ["midwest", "great-lakes"],
    memberEstimate: 2_200_000,
    commercial: true,
    medicare: true,
    medicaid: false,
    exchange: true,
    publicCompany: false,
    tags: ["blues", "midwest", "regional"],
    buyerPack: "health-plans",
  },
];

export function getHealthPlanById(id: string): OrganizationRecord | undefined {
  return HEALTH_PLANS_DIRECTORY.find((r) => r.id === id);
}

export function getHealthPlanByNameOrAlias(token: string): OrganizationRecord | undefined {
  const norm = token.trim().toLowerCase();
  if (!norm) return undefined;
  return HEALTH_PLANS_DIRECTORY.find(
    (r) =>
      r.name.toLowerCase() === norm ||
      r.aliases.some((a) => a.toLowerCase() === norm) ||
      r.name.toLowerCase().includes(norm) ||
      r.aliases.some((a) => a.includes(norm)),
  );
}
