import type { OrganizationRecord } from "./types";

export const NONPROFITS_DIRECTORY: OrganizationRecord[] = [
  {
    id: "dir-npo-cleveland-clinic-foundation",
    name: "Cleveland Clinic Foundation",
    aliases: ["cleveland clinic foundation"],
    organizationType: "employer",
    sectorId: "nonprofit",
    industryId: "nonprofit",
    organizationTypeId: "employer",
    industry: "nonprofit",
    website: "https://my.clevelandclinic.org",
    headquarters: "Cleveland, OH",
    statesServed: ["OH", "FL", "NV"],
    regions: ["midwest", "national"],
    employeeEstimate: 75_000,
    publicCompany: false,
    tags: ["nonprofit", "healthcare", "ohio"],
    knownSignals: [],
    relevantProviders: ["news-rss", "company-site"],
    buyerPack: "employers",
  },
  {
    id: "dir-npo-feeding-america",
    name: "Feeding America (Ohio Foodbank Network)",
    aliases: ["feeding america ohio", "mid-ohio foodbank"],
    organizationType: "employer",
    sectorId: "nonprofit",
    industryId: "nonprofit",
    organizationTypeId: "employer",
    industry: "nonprofit",
    website: "https://www.feedingamerica.org",
    headquarters: "Columbus, OH",
    statesServed: ["OH"],
    regions: ["midwest"],
    employeeEstimate: 500,
    publicCompany: false,
    tags: ["nonprofit", "food bank", "ohio"],
    knownSignals: [],
    relevantProviders: ["news-rss", "company-site"],
    buyerPack: "employers",
  },
];
