import type { OrganizationRecord } from "./types";

type Mfg = Omit<OrganizationRecord, "buyerPack" | "organizationType"> & {
  organizationType?: OrganizationRecord["organizationType"];
};

function mfg(partial: Mfg): OrganizationRecord {
  return {
    organizationType: "manufacturer",
    buyerPack: "manufacturers",
    ...partial,
  };
}

/** Curated Ohio manufacturers — food, pharma, industrial, packaging, CPG, chemicals, automotive, med devices. */
export const OHIO_MANUFACTURERS: OrganizationRecord[] = [
  // Food & Beverage
  mfg({
    id: "dir-mfg-oh-smucker",
    name: "The J.M. Smucker Company",
    aliases: ["smucker", "jm smucker", "j m smucker"],
    sectorId: "manufacturing",
    industryId: "food-beverage",
    organizationTypeId: "food-beverage-company",
    industry: "food-beverage",
    website: "https://www.jmsmucker.com",
    headquarters: "Orrville, OH",
    statesServed: ["OH", "PA", "MI", "IN", "KY"],
    regions: ["midwest", "national"],
    employeeEstimate: 7_000,
    publicCompany: true,
    ticker: "SJM",
    tags: ["food", "cpg", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "fda", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-lancaster",
    name: "Lancaster Colony Corporation",
    aliases: ["lancaster colony"],
    sectorId: "manufacturing",
    industryId: "food-beverage",
    organizationTypeId: "food-beverage-company",
    industry: "food-beverage",
    website: "https://www.lancastercolony.com",
    headquarters: "Westerville, OH",
    statesServed: ["OH", "IN", "KY", "PA"],
    regions: ["midwest"],
    employeeEstimate: 3_200,
    publicCompany: true,
    ticker: "LANC",
    tags: ["food", "specialty foods", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "fda", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-shearers",
    name: "Shearer's Foods",
    aliases: ["shearers snacks", "shearer's"],
    sectorId: "manufacturing",
    industryId: "food-beverage",
    organizationTypeId: "food-beverage-company",
    industry: "food-beverage",
    website: "https://www.shearers.com",
    headquarters: "Massillon, OH",
    statesServed: ["OH", "PA", "IN", "MI"],
    regions: ["midwest"],
    employeeEstimate: 5_000,
    publicCompany: false,
    tags: ["food", "snacks", "private", "ohio"],
    knownSignals: [],
    relevantProviders: ["fda", "news-rss", "company-site"],
  }),
  mfg({
    id: "dir-mfg-oh-sunnyd",
    name: "Sunny Delight Beverages",
    aliases: ["sunny d", "sunny delight"],
    sectorId: "manufacturing",
    industryId: "food-beverage",
    organizationTypeId: "food-beverage-company",
    industry: "food-beverage",
    website: "https://www.sunnyd.com",
    headquarters: "Cincinnati, OH",
    statesServed: ["OH", "KY", "IN"],
    regions: ["midwest", "national"],
    employeeEstimate: 1_500,
    publicCompany: false,
    tags: ["beverage", "private", "ohio"],
    knownSignals: [],
    relevantProviders: ["fda", "news-rss", "company-site"],
  }),
  mfg({
    id: "dir-mfg-oh-nestle-solon",
    name: "Nestlé USA Solon Operations",
    aliases: ["nestle solon", "nestle pizza", "digiorno"],
    sectorId: "manufacturing",
    industryId: "food-beverage",
    organizationTypeId: "food-beverage-company",
    industry: "food-beverage",
    website: "https://www.nestleusa.com",
    headquarters: "Solon, OH",
    statesServed: ["OH", "PA", "MI"],
    regions: ["midwest"],
    employeeEstimate: 2_000,
    publicCompany: false,
    tags: ["food", "frozen foods", "ohio"],
    knownSignals: [],
    relevantProviders: ["fda", "news-rss", "company-site"],
  }),
  mfg({
    id: "dir-mfg-oh-campbell",
    name: "Campbell Soup Company (Ohio Operations)",
    aliases: ["campbell soup", "campbell's"],
    sectorId: "manufacturing",
    industryId: "food-beverage",
    organizationTypeId: "food-beverage-company",
    industry: "food-beverage",
    website: "https://www.campbells.com",
    headquarters: "Napoleon, OH",
    statesServed: ["OH", "MI", "IN"],
    regions: ["midwest", "national"],
    employeeEstimate: 1_800,
    publicCompany: true,
    ticker: "CPB",
    tags: ["food", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "fda", "news-rss"],
  }),
  // Pharma / Life Sciences
  mfg({
    id: "dir-mfg-oh-cardinal",
    name: "Cardinal Health",
    aliases: ["cardinal health inc"],
    sectorId: "healthcare",
    industryId: "life-sciences",
    organizationTypeId: "pharma-manufacturer",
    industry: "life-sciences",
    website: "https://www.cardinalhealth.com",
    headquarters: "Dublin, OH",
    statesServed: ["OH", "PA", "MI", "IN", "KY", "CA", "TX"],
    regions: ["midwest", "national"],
    employeeEstimate: 48_000,
    publicCompany: true,
    ticker: "CAH",
    tags: ["pharma", "distribution", "large-cap", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "fda", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-boehringer",
    name: "Boehringer Ingelheim (Fremont)",
    aliases: ["boehringer ingelheim fremont", "boehringer"],
    sectorId: "healthcare",
    industryId: "life-sciences",
    organizationTypeId: "pharma-manufacturer",
    industry: "life-sciences",
    website: "https://www.boehringer-ingelheim.com",
    headquarters: "Fremont, OH",
    statesServed: ["OH", "MI", "IN"],
    regions: ["midwest"],
    employeeEstimate: 1_200,
    publicCompany: false,
    tags: ["pharma", "biotech", "ohio"],
    knownSignals: [],
    relevantProviders: ["fda", "news-rss", "company-site"],
  }),
  mfg({
    id: "dir-mfg-oh-amgen",
    name: "Amgen (West Chester)",
    aliases: ["amgen west chester", "amgen ohio"],
    sectorId: "healthcare",
    industryId: "life-sciences",
    organizationTypeId: "pharma-manufacturer",
    industry: "life-sciences",
    website: "https://www.amgen.com",
    headquarters: "West Chester, OH",
    statesServed: ["OH", "KY", "IN"],
    regions: ["midwest", "national"],
    employeeEstimate: 1_500,
    publicCompany: true,
    ticker: "AMGN",
    tags: ["pharma", "biotech", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "fda", "news-rss"],
  }),
  // Industrial Products
  mfg({
    id: "dir-mfg-oh-parker",
    name: "Parker Hannifin",
    aliases: ["parker hannifin corporation", "parker"],
    sectorId: "manufacturing",
    industryId: "industrial-products",
    organizationTypeId: "manufacturer",
    industry: "industrial-products",
    website: "https://www.parker.com",
    headquarters: "Cleveland, OH",
    statesServed: ["OH", "PA", "MI", "IN", "KY"],
    regions: ["midwest", "national"],
    employeeEstimate: 62_000,
    publicCompany: true,
    ticker: "PH",
    tags: ["industrial", "motion control", "large-cap", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-eaton",
    name: "Eaton Corporation",
    aliases: ["eaton corp", "eaton"],
    sectorId: "manufacturing",
    industryId: "industrial-products",
    organizationTypeId: "manufacturer",
    industry: "industrial-products",
    website: "https://www.eaton.com",
    headquarters: "Cleveland, OH",
    statesServed: ["OH", "PA", "MI", "IN", "KY"],
    regions: ["midwest", "national"],
    employeeEstimate: 92_000,
    publicCompany: true,
    ticker: "ETN",
    tags: ["industrial", "electrical", "large-cap", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-timken",
    name: "The Timken Company",
    aliases: ["timken", "timken company"],
    sectorId: "manufacturing",
    industryId: "industrial-products",
    organizationTypeId: "manufacturer",
    industry: "industrial-products",
    website: "https://www.timken.com",
    headquarters: "North Canton, OH",
    statesServed: ["OH", "PA", "MI", "IN"],
    regions: ["midwest", "national"],
    employeeEstimate: 19_000,
    publicCompany: true,
    ticker: "TKR",
    tags: ["industrial", "bearings", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-lincoln",
    name: "Lincoln Electric",
    aliases: ["lincoln electric company", "lincoln electric"],
    sectorId: "manufacturing",
    industryId: "industrial-products",
    organizationTypeId: "manufacturer",
    industry: "industrial-products",
    website: "https://www.lincolnelectric.com",
    headquarters: "Cleveland, OH",
    statesServed: ["OH", "PA", "MI"],
    regions: ["midwest", "national"],
    employeeEstimate: 11_000,
    publicCompany: true,
    ticker: "LECO",
    tags: ["industrial", "welding", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-owens",
    name: "Owens Corning",
    aliases: ["owens corning corporation"],
    sectorId: "manufacturing",
    industryId: "industrial-products",
    organizationTypeId: "manufacturer",
    industry: "industrial-products",
    website: "https://www.owenscorning.com",
    headquarters: "Toledo, OH",
    statesServed: ["OH", "MI", "IN", "PA"],
    regions: ["midwest", "national"],
    employeeEstimate: 19_000,
    publicCompany: true,
    ticker: "OC",
    tags: ["industrial", "building materials", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-worthington",
    name: "Worthington Industries",
    aliases: ["worthington steel", "worthington"],
    sectorId: "manufacturing",
    industryId: "industrial-products",
    organizationTypeId: "manufacturer",
    industry: "industrial-products",
    website: "https://www.worthingtonindustries.com",
    headquarters: "Columbus, OH",
    statesServed: ["OH", "PA", "MI", "IN", "KY"],
    regions: ["midwest", "national"],
    employeeEstimate: 9_500,
    publicCompany: true,
    ticker: "WOR",
    tags: ["industrial", "steel", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-cliffs",
    name: "Cleveland-Cliffs",
    aliases: ["cleveland cliffs", "ak steel", "clf"],
    sectorId: "manufacturing",
    industryId: "industrial-products",
    organizationTypeId: "manufacturer",
    industry: "industrial-products",
    website: "https://www.clevelandcliffs.com",
    headquarters: "Cleveland, OH",
    statesServed: ["OH", "PA", "MI", "IN"],
    regions: ["midwest", "national"],
    employeeEstimate: 27_000,
    publicCompany: true,
    ticker: "CLF",
    tags: ["industrial", "steel", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
  }),
  // Packaging
  mfg({
    id: "dir-mfg-oh-greif",
    name: "Greif Inc.",
    aliases: ["greif", "greif brothers"],
    sectorId: "manufacturing",
    industryId: "packaging",
    organizationTypeId: "packaging-company",
    industry: "packaging",
    website: "https://www.greif.com",
    headquarters: "Delaware, OH",
    statesServed: ["OH", "PA", "MI", "IN", "KY"],
    regions: ["midwest", "national"],
    employeeEstimate: 14_000,
    publicCompany: true,
    ticker: "GEF",
    tags: ["packaging", "industrial packaging", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "fda", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-berry",
    name: "Berry Global (Sidney Operations)",
    aliases: ["berry global", "berry plastics sidney"],
    sectorId: "manufacturing",
    industryId: "packaging",
    organizationTypeId: "packaging-company",
    industry: "packaging",
    website: "https://www.berryglobal.com",
    headquarters: "Sidney, OH",
    statesServed: ["OH", "IN", "MI", "PA"],
    regions: ["midwest", "national"],
    employeeEstimate: 3_500,
    publicCompany: true,
    ticker: "BERY",
    tags: ["packaging", "plastics", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "fda", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-silgan",
    name: "Silgan Containers (Ohio Operations)",
    aliases: ["silgan", "silgan containers"],
    sectorId: "manufacturing",
    industryId: "packaging",
    organizationTypeId: "packaging-company",
    industry: "packaging",
    website: "https://www.silgancontainers.com",
    headquarters: "Cincinnati, OH",
    statesServed: ["OH", "KY", "IN", "PA"],
    regions: ["midwest", "national"],
    employeeEstimate: 2_000,
    publicCompany: true,
    ticker: "SLGN",
    tags: ["packaging", "metal containers", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "fda", "news-rss"],
  }),
  // Consumer Goods
  mfg({
    id: "dir-mfg-oh-pg",
    name: "Procter & Gamble",
    aliases: ["p&g", "procter and gamble", "pg"],
    sectorId: "manufacturing",
    industryId: "consumer-goods",
    organizationTypeId: "consumer-goods-company",
    industry: "consumer-goods",
    website: "https://www.pg.com",
    headquarters: "Cincinnati, OH",
    statesServed: ["OH", "KY", "IN", "PA", "MI"],
    regions: ["midwest", "national"],
    employeeEstimate: 107_000,
    publicCompany: true,
    ticker: "PG",
    tags: ["cpg", "household", "large-cap", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "fda", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-henkel",
    name: "Henkel (North American Consumer Goods)",
    aliases: ["henkel", "henkel consumer goods"],
    sectorId: "manufacturing",
    industryId: "consumer-goods",
    organizationTypeId: "consumer-goods-company",
    industry: "consumer-goods",
    website: "https://www.henkel-northamerica.com",
    headquarters: "West Chester, OH",
    statesServed: ["OH", "KY", "IN"],
    regions: ["midwest", "national"],
    employeeEstimate: 4_000,
    publicCompany: false,
    tags: ["cpg", "adhesives", "ohio"],
    knownSignals: [],
    relevantProviders: ["fda", "news-rss", "company-site"],
  }),
  mfg({
    id: "dir-mfg-oh-scotts",
    name: "The Scotts Miracle-Gro Company",
    aliases: ["scotts", "miracle-gro", "scotts miracle gro"],
    sectorId: "manufacturing",
    industryId: "consumer-goods",
    organizationTypeId: "consumer-goods-company",
    industry: "consumer-goods",
    website: "https://www.scotts.com",
    headquarters: "Marysville, OH",
    statesServed: ["OH", "PA", "MI", "IN", "KY"],
    regions: ["midwest", "national"],
    employeeEstimate: 6_000,
    publicCompany: true,
    ticker: "SMG",
    tags: ["cpg", "lawn garden", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "fda", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-gojo",
    name: "GOJO Industries",
    aliases: ["gojo", "purell", "gojo industries"],
    sectorId: "manufacturing",
    industryId: "consumer-goods",
    organizationTypeId: "consumer-goods-company",
    industry: "consumer-goods",
    website: "https://www.gojo.com",
    headquarters: "Akron, OH",
    statesServed: ["OH", "PA", "MI"],
    regions: ["midwest", "national"],
    employeeEstimate: 2_500,
    publicCompany: false,
    tags: ["cpg", "sanitizer", "private", "ohio"],
    knownSignals: [],
    relevantProviders: ["fda", "news-rss", "company-site"],
  }),
  // Chemicals
  mfg({
    id: "dir-mfg-oh-lubrizol",
    name: "Lubrizol Corporation",
    aliases: ["lubrizol", "berkshire lubrizol"],
    sectorId: "manufacturing",
    industryId: "chemicals",
    organizationTypeId: "chemical-company",
    industry: "chemicals",
    website: "https://www.lubrizol.com",
    headquarters: "Wickliffe, OH",
    statesServed: ["OH", "PA", "MI", "IN"],
    regions: ["midwest", "national"],
    employeeEstimate: 8_800,
    publicCompany: false,
    tags: ["chemicals", "specialty chemical", "private", "ohio"],
    knownSignals: [],
    relevantProviders: ["fda", "news-rss", "company-site"],
  }),
  mfg({
    id: "dir-mfg-oh-sherwin",
    name: "Sherwin-Williams",
    aliases: ["sherwin williams", "sherwin-williams company"],
    sectorId: "manufacturing",
    industryId: "chemicals",
    organizationTypeId: "chemical-company",
    industry: "chemicals",
    website: "https://www.sherwin-williams.com",
    headquarters: "Cleveland, OH",
    statesServed: ["OH", "PA", "MI", "IN", "KY"],
    regions: ["midwest", "national"],
    employeeEstimate: 64_000,
    publicCompany: true,
    ticker: "SHW",
    tags: ["chemicals", "coatings", "paint", "large-cap", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "fda", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-hexion",
    name: "Hexion Inc.",
    aliases: ["hexion", "hexion specialty chemicals"],
    sectorId: "manufacturing",
    industryId: "chemicals",
    organizationTypeId: "chemical-company",
    industry: "chemicals",
    website: "https://www.hexion.com",
    headquarters: "Columbus, OH",
    statesServed: ["OH", "PA", "MI", "IN"],
    regions: ["midwest", "national"],
    employeeEstimate: 4_500,
    publicCompany: false,
    tags: ["chemicals", "resins", "private", "ohio"],
    knownSignals: [],
    relevantProviders: ["fda", "news-rss", "company-site"],
  }),
  // Automotive
  mfg({
    id: "dir-mfg-oh-honda",
    name: "Honda of America Manufacturing",
    aliases: ["honda ohio", "honda marysville", "honda of america"],
    sectorId: "manufacturing",
    industryId: "automotive",
    organizationTypeId: "automotive-manufacturer",
    industry: "automotive",
    website: "https://www.honda.com",
    headquarters: "Marysville, OH",
    statesServed: ["OH", "IN", "KY", "MI"],
    regions: ["midwest", "national"],
    employeeEstimate: 15_000,
    publicCompany: false,
    tags: ["automotive", "oem", "ohio"],
    knownSignals: [],
    relevantProviders: ["news-rss", "company-site"],
  }),
  mfg({
    id: "dir-mfg-oh-dana",
    name: "Dana Incorporated",
    aliases: ["dana corp", "dana inc"],
    sectorId: "manufacturing",
    industryId: "automotive",
    organizationTypeId: "automotive-manufacturer",
    industry: "automotive",
    website: "https://www.dana.com",
    headquarters: "Maumee, OH",
    statesServed: ["OH", "MI", "IN", "KY", "PA"],
    regions: ["midwest", "national"],
    employeeEstimate: 42_000,
    publicCompany: true,
    ticker: "DAN",
    tags: ["automotive", "auto parts", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-goodyear",
    name: "The Goodyear Tire & Rubber Company",
    aliases: ["goodyear", "goodyear tire"],
    sectorId: "manufacturing",
    industryId: "automotive",
    organizationTypeId: "automotive-manufacturer",
    industry: "automotive",
    website: "https://www.goodyear.com",
    headquarters: "Akron, OH",
    statesServed: ["OH", "PA", "MI", "IN", "KY"],
    regions: ["midwest", "national"],
    employeeEstimate: 72_000,
    publicCompany: true,
    ticker: "GT",
    tags: ["automotive", "tires", "large-cap", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
  }),
  // Medical Devices
  mfg({
    id: "dir-mfg-oh-steris",
    name: "STERIS plc",
    aliases: ["steris", "steris corporation"],
    sectorId: "healthcare",
    industryId: "medical-device-manufacturing",
    organizationTypeId: "medical-device",
    industry: "medical-device-manufacturing",
    website: "https://www.steris.com",
    headquarters: "Mentor, OH",
    statesServed: ["OH", "PA", "MI", "IN"],
    regions: ["midwest", "national"],
    employeeEstimate: 17_000,
    publicCompany: true,
    ticker: "STE",
    tags: ["medical device", "sterilization", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "fda", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-invacare",
    name: "Invacare Corporation",
    aliases: ["invacare"],
    sectorId: "healthcare",
    industryId: "medical-device-manufacturing",
    organizationTypeId: "medical-device",
    industry: "medical-device-manufacturing",
    website: "https://www.invacare.com",
    headquarters: "Elyria, OH",
    statesServed: ["OH", "PA", "MI", "IN"],
    regions: ["midwest", "national"],
    employeeEstimate: 3_000,
    publicCompany: true,
    ticker: "IVC",
    tags: ["medical device", "mobility", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "fda", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-atricure",
    name: "AtriCure",
    aliases: ["atricure inc"],
    sectorId: "healthcare",
    industryId: "medical-device-manufacturing",
    organizationTypeId: "medical-device",
    industry: "medical-device-manufacturing",
    website: "https://www.atricure.com",
    headquarters: "Mason, OH",
    statesServed: ["OH", "KY", "IN"],
    regions: ["midwest", "national"],
    employeeEstimate: 1_200,
    publicCompany: true,
    ticker: "ATRC",
    tags: ["medical device", "surgical", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "fda", "news-rss"],
  }),
  mfg({
    id: "dir-mfg-oh-integer",
    name: "Integer Holdings (Cleveland Operations)",
    aliases: ["integer holdings", "greatbatch integer"],
    sectorId: "healthcare",
    industryId: "medical-device-manufacturing",
    organizationTypeId: "medical-device",
    industry: "medical-device-manufacturing",
    website: "https://www.integer.net",
    headquarters: "Cleveland, OH",
    statesServed: ["OH", "PA", "MI"],
    regions: ["midwest", "national"],
    employeeEstimate: 2_500,
    publicCompany: true,
    ticker: "ITGR",
    tags: ["medical device", "components", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "fda", "news-rss"],
  }),
];
