import type { OrganizationRecord } from "./types";

export const PUBLIC_SECTOR_DIRECTORY: OrganizationRecord[] = [
  {
    id: "dir-ps-columbus",
    name: "City of Columbus",
    aliases: ["columbus ohio", "city of columbus oh"],
    organizationType: "municipality",
    sectorId: "public-sector",
    industryId: "municipalities",
    organizationTypeId: "municipality",
    industry: "municipalities",
    website: "https://www.columbus.gov",
    headquarters: "Columbus, OH",
    statesServed: ["OH"],
    regions: ["midwest"],
    employeeEstimate: 8_500,
    tags: ["municipal", "ohio"],
    knownSignals: [],
    relevantProviders: ["company-site", "news-rss"],
    buyerPack: "public-sector",
  },
  {
    id: "dir-ps-cleveland",
    name: "City of Cleveland",
    aliases: ["cleveland ohio", "city of cleveland"],
    organizationType: "municipality",
    sectorId: "public-sector",
    industryId: "municipalities",
    organizationTypeId: "municipality",
    industry: "municipalities",
    website: "https://www.clevelandohio.gov",
    headquarters: "Cleveland, OH",
    statesServed: ["OH"],
    regions: ["midwest"],
    employeeEstimate: 7_000,
    tags: ["municipal", "ohio"],
    knownSignals: [],
    relevantProviders: ["company-site", "news-rss"],
    buyerPack: "public-sector",
  },
  {
    id: "dir-ps-philly",
    name: "City of Philadelphia",
    aliases: ["philadelphia", "city of philadelphia"],
    organizationType: "municipality",
    sectorId: "public-sector",
    industryId: "municipalities",
    organizationTypeId: "municipality",
    industry: "municipalities",
    website: "https://www.phila.gov",
    headquarters: "Philadelphia, PA",
    statesServed: ["PA"],
    regions: ["mid-atlantic", "northeast"],
    employeeEstimate: 25_000,
    tags: ["municipal", "pennsylvania"],
    knownSignals: [],
    relevantProviders: ["company-site", "news-rss"],
    buyerPack: "public-sector",
  },
  {
    id: "dir-ps-pittsburgh",
    name: "City of Pittsburgh",
    aliases: ["pittsburgh", "city of pittsburgh"],
    organizationType: "municipality",
    sectorId: "public-sector",
    industryId: "municipalities",
    organizationTypeId: "municipality",
    industry: "municipalities",
    website: "https://www.pittsburghpa.gov",
    headquarters: "Pittsburgh, PA",
    statesServed: ["PA"],
    regions: ["mid-atlantic", "northeast"],
    employeeEstimate: 3_500,
    tags: ["municipal", "pennsylvania"],
    knownSignals: [],
    relevantProviders: ["company-site", "news-rss"],
    buyerPack: "public-sector",
  },
  {
    id: "dir-ps-septa",
    name: "SEPTA",
    aliases: ["southeastern pennsylvania transportation authority"],
    organizationType: "municipality",
    sectorId: "public-sector",
    industryId: "transit-authorities",
    organizationTypeId: "transit-authority",
    industry: "transit-authorities",
    website: "https://www.septa.org",
    headquarters: "Philadelphia, PA",
    statesServed: ["PA"],
    regions: ["mid-atlantic", "northeast"],
    employeeEstimate: 9_500,
    tags: ["transit", "pennsylvania"],
    knownSignals: [],
    relevantProviders: ["company-site", "news-rss"],
    buyerPack: "public-sector",
  },
];
