import type { OrganizationRecord } from "./types";

export const RETAIL_CONSUMER_DIRECTORY: OrganizationRecord[] = [
  {
    id: "dir-ret-kroger",
    name: "The Kroger Co.",
    aliases: ["kroger", "kroger company"],
    organizationType: "employer",
    sectorId: "retail-consumer",
    industryId: "retail",
    organizationTypeId: "employer",
    industry: "retail",
    website: "https://www.kroger.com",
    headquarters: "Cincinnati, OH",
    statesServed: ["OH", "KY", "IN", "MI", "PA"],
    regions: ["midwest", "national"],
    employeeEstimate: 430_000,
    publicCompany: true,
    ticker: "KR",
    tags: ["grocery", "retail", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
    buyerPack: "employers",
  },
  {
    id: "dir-ret-giant-eagle",
    name: "Giant Eagle",
    aliases: ["giant eagle inc"],
    organizationType: "employer",
    sectorId: "retail-consumer",
    industryId: "retail",
    organizationTypeId: "employer",
    industry: "retail",
    website: "https://www.gianteagle.com",
    headquarters: "Pittsburgh, PA",
    statesServed: ["PA", "OH", "WV", "MD", "IN"],
    regions: ["mid-atlantic", "midwest"],
    employeeEstimate: 35_000,
    publicCompany: false,
    tags: ["grocery", "retail", "pennsylvania"],
    knownSignals: [],
    relevantProviders: ["news-rss", "company-site"],
    buyerPack: "employers",
  },
];
