import type { OrganizationRecord } from "./types";

export const TECHNOLOGY_DIRECTORY: OrganizationRecord[] = [
  {
    id: "dir-tech-diebold",
    name: "Diebold Nixdorf",
    aliases: ["diebold nixdorf", "diebold"],
    organizationType: "employer",
    sectorId: "technology",
    industryId: "technology",
    organizationTypeId: "employer",
    industry: "technology",
    website: "https://www.dieboldnixdorf.com",
    headquarters: "North Canton, OH",
    statesServed: ["OH", "PA", "MI"],
    regions: ["midwest", "national"],
    employeeEstimate: 22_000,
    publicCompany: true,
    ticker: "DBD",
    tags: ["software", "hardware", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
    buyerPack: "employers",
  },
  {
    id: "dir-tech-root",
    name: "Root Inc.",
    aliases: ["root insurance", "root inc"],
    organizationType: "employer",
    sectorId: "technology",
    industryId: "fintech",
    organizationTypeId: "fintech-company",
    industry: "fintech",
    website: "https://www.joinroot.com",
    headquarters: "Columbus, OH",
    statesServed: ["OH"],
    regions: ["midwest", "national"],
    employeeEstimate: 1_200,
    publicCompany: true,
    ticker: "ROOT",
    tags: ["insurtech", "fintech", "ohio"],
    knownSignals: [],
    relevantProviders: ["sec-edgar", "news-rss"],
    buyerPack: "employers",
  },
];
