import type { ParentDomainRule } from "./types";
import { normalizeBrandPhrase } from "./normalize";

function rule(
  input: Omit<ParentDomainRule, "parentNames" | "entityTokens"> & {
    parentNames?: string[];
    entityTokens?: string[];
  },
): ParentDomainRule {
  return {
    parentNames: input.parentNames ?? [],
    entityTokens: input.entityTokens ?? [],
    ...input,
  };
}

/** Lane 1 — hand-curated national and obvious parent → domain rules. */
export const CURATED_PARENT_DOMAIN_RULES: ParentDomainRule[] = [
  rule({
    id: "parent-uhc",
    parentOrg: "UnitedHealth Group",
    domain: "uhc.com",
    website: "https://www.uhc.com",
    confidence: 0.92,
    national: true,
    parentNames: ["unitedhealth group", "unitedhealth group incorporated", "unitedhealth"],
    entityTokens: ["unitedhealthcare", "united healthcare", "uhc"],
    excludeTokens: ["optum", "mine workers"],
  }),
  rule({
    id: "parent-optum",
    parentOrg: "UnitedHealth Group",
    domain: "optum.com",
    website: "https://www.optum.com",
    confidence: 0.9,
    national: true,
    entityTokens: ["optum"],
  }),
  rule({
    id: "parent-aetna",
    parentOrg: "CVS Health",
    domain: "aetna.com",
    website: "https://www.aetna.com",
    confidence: 0.91,
    national: true,
    parentNames: ["cvs health", "cvs health corporation"],
    entityTokens: ["aetna"],
  }),
  rule({
    id: "parent-cigna",
    parentOrg: "The Cigna Group",
    domain: "cigna.com",
    website: "https://www.cigna.com",
    confidence: 0.91,
    national: true,
    parentNames: ["the cigna group", "cigna group", "cigna corporation"],
    entityTokens: ["cigna healthcare", "cigna health"],
    excludeTokens: ["express scripts", "evernorth"],
  }),
  rule({
    id: "parent-evernorth",
    parentOrg: "The Cigna Group",
    domain: "evernorth.com",
    website: "https://www.evernorth.com",
    confidence: 0.91,
    national: true,
    parentNames: ["evernorth", "evernorth health"],
    entityTokens: ["evernorth"],
    excludeTokens: ["cigna healthcare", "cigna health"],
  }),
  rule({
    id: "parent-express-scripts",
    parentOrg: "The Cigna Group",
    domain: "express-scripts.com",
    website: "https://www.express-scripts.com",
    confidence: 0.9,
    national: true,
    entityTokens: ["express scripts"],
  }),
  rule({
    id: "parent-humana",
    parentOrg: "Humana Inc.",
    domain: "humana.com",
    website: "https://www.humana.com",
    confidence: 0.92,
    national: true,
    parentNames: ["humana inc", "humana incorporated"],
    entityTokens: ["humana"],
  }),
  rule({
    id: "parent-elevance",
    parentOrg: "Elevance Health, Inc.",
    domain: "elevancehealth.com",
    website: "https://www.elevancehealth.com",
    confidence: 0.9,
    national: true,
    parentNames: ["elevance health", "elevance health inc", "wellpoint", "wellpoint inc"],
    entityTokens: ["elevance health"],
  }),
  rule({
    id: "parent-anthem",
    parentOrg: "Elevance Health, Inc.",
    domain: "elevancehealth.com",
    website: "https://www.elevancehealth.com",
    confidence: 0.89,
    national: true,
    entityTokens: ["anthem blue cross", "anthem bcbs"],
    excludeTokens: ["wisconsin", "ohio", "indiana", "kentucky", "connecticut"],
  }),
  rule({
    id: "parent-kaiser",
    parentOrg: "Kaiser Foundation Health Plan, Inc.",
    domain: "kp.org",
    website: "https://www.kp.org",
    confidence: 0.92,
    national: true,
    parentNames: [
      "kaiser foundation health plan",
      "kaiser foundation health plan inc",
      "kaiser permanente",
    ],
    entityTokens: ["kaiser permanente", "kaiser foundation"],
  }),
  rule({
    id: "parent-centene",
    parentOrg: "Centene Corporation",
    domain: "centene.com",
    website: "https://www.centene.com",
    confidence: 0.91,
    national: true,
    parentNames: ["centene corporation", "centene corp"],
    entityTokens: ["centene"],
    excludeTokens: [
      "wellcare",
      "sunshine",
      "buckeye",
      "absolute total",
      "peach state",
      "superior health",
      "magnolia health",
      "carolina complete",
      "keystone first",
      "health net",
    ],
  }),
  rule({
    id: "parent-wellcare",
    parentOrg: "Centene Corporation",
    domain: "wellcare.com",
    website: "https://www.wellcare.com",
    confidence: 0.9,
    national: true,
    entityTokens: ["wellcare"],
  }),
  rule({
    id: "parent-molina",
    parentOrg: "Molina Healthcare, Inc.",
    domain: "molinahealthcare.com",
    website: "https://www.molinahealthcare.com",
    confidence: 0.91,
    national: true,
    parentNames: ["molina healthcare", "molina healthcare inc"],
    entityTokens: ["molina healthcare", "molina health"],
  }),
  rule({
    id: "parent-florida-blue",
    parentOrg: "Guidewell Mutual Holding Corporation",
    domain: "floridablue.com",
    website: "https://www.floridablue.com",
    confidence: 0.91,
    national: true,
    parentNames: [
      "guidewell mutual holding corporation",
      "guidewell",
      "florida blue",
    ],
    entityTokens: ["florida blue", "blue cross blue shield of florida"],
  }),
  rule({
    id: "parent-bcbs-mi",
    parentOrg: "Blue Cross Blue Shield of Michigan",
    domain: "bcbsm.com",
    website: "https://www.bcbsm.com",
    confidence: 0.91,
    states: ["MI"],
    parentNames: [
      normalizeBrandPhrase("Blue Cross Blue Shield of Michigan"),
      "bcbs of michigan",
    ],
    entityTokens: ["blue cross blue shield of michigan", "bcbs of michigan"],
  }),
  rule({
    id: "parent-bcbs-al",
    parentOrg: "Blue Cross and Blue Shield of Alabama",
    domain: "bcbsal.org",
    website: "https://www.bcbsal.org",
    confidence: 0.91,
    states: ["AL"],
    entityTokens: ["blue cross blue shield of alabama", "bcbs of alabama"],
  }),
  rule({
    id: "parent-bcbs-il",
    parentOrg: "Health Care Service Corporation",
    domain: "bcbsil.com",
    website: "https://www.bcbsil.com",
    confidence: 0.91,
    states: ["IL"],
    parentNames: [normalizeBrandPhrase("Health Care Service Corporation")],
    entityTokens: ["blue cross blue shield of illinois", "bcbs of illinois"],
  }),
  rule({
    id: "parent-bcbs-tx",
    parentOrg: "Health Care Service Corporation",
    domain: "bcbstx.com",
    website: "https://www.bcbstx.com",
    confidence: 0.91,
    states: ["TX"],
    entityTokens: ["blue cross blue shield of texas", "bcbs of texas"],
  }),
  rule({
    id: "parent-bcbs-ok",
    parentOrg: "Health Care Service Corporation",
    domain: "bcbsok.com",
    website: "https://www.bcbsok.com",
    confidence: 0.91,
    states: ["OK"],
    entityTokens: ["blue cross blue shield of oklahoma", "bcbs of oklahoma"],
  }),
  rule({
    id: "parent-bcbs-nm",
    parentOrg: "Health Care Service Corporation",
    domain: "bcbsnm.com",
    website: "https://www.bcbsnm.com",
    confidence: 0.91,
    states: ["NM"],
    entityTokens: ["blue cross blue shield of new mexico", "bcbs of new mexico"],
  }),
  rule({
    id: "parent-bcbs-mt",
    parentOrg: "Health Care Service Corporation",
    domain: "bcbsmt.com",
    website: "https://www.bcbsmt.com",
    confidence: 0.91,
    states: ["MT"],
    entityTokens: ["blue cross blue shield of montana", "bcbs of montana"],
  }),
  rule({
    id: "parent-bcbs-nc",
    parentOrg: "Blue Cross and Blue Shield of North Carolina",
    domain: "bluecrossnc.com",
    website: "https://www.bluecrossnc.com",
    confidence: 0.91,
    states: ["NC"],
    entityTokens: ["blue cross blue shield of north carolina", "bcbs of north carolina"],
  }),
  rule({
    id: "parent-bcbs-sc",
    parentOrg: "BlueCross BlueShield of South Carolina",
    domain: "southcarolinablues.com",
    website: "https://www.southcarolinablues.com",
    confidence: 0.91,
    states: ["SC"],
    entityTokens: ["bluecross blueshield of south carolina", "bcbs of south carolina"],
  }),
  rule({
    id: "parent-bcbs-la",
    parentOrg: "Blue Cross and Blue Shield of Louisiana",
    domain: "bcbsla.com",
    website: "https://www.bcbsla.com",
    confidence: 0.91,
    states: ["LA"],
    entityTokens: ["blue cross blue shield of louisiana", "bcbs of louisiana"],
  }),
  rule({
    id: "parent-bcbs-az",
    parentOrg: "Blue Cross Blue Shield of Arizona",
    domain: "azblue.com",
    website: "https://www.azblue.com",
    confidence: 0.91,
    states: ["AZ"],
    entityTokens: ["blue cross blue shield of arizona", "bcbs of arizona"],
  }),
  rule({
    id: "parent-highmark",
    parentOrg: "Highmark Health",
    domain: "highmark.com",
    website: "https://www.highmark.com",
    confidence: 0.9,
    states: ["PA", "WV", "DE", "NY"],
    parentNames: [normalizeBrandPhrase("Highmark Health"), "highmark inc"],
    entityTokens: ["highmark"],
  }),
  rule({
    id: "parent-ibx",
    parentOrg: "Independence Health Group",
    domain: "ibx.com",
    website: "https://www.ibx.com",
    confidence: 0.9,
    states: ["PA", "NJ"],
    parentNames: [normalizeBrandPhrase("Independence Health Group")],
    entityTokens: ["independence blue cross"],
  }),
  // Batch #2 — high-confidence national/regional parent mappings
  rule({
    id: "parent-blue-shield-ca",
    parentOrg: "Blue Shield of California",
    domain: "blueshieldca.com",
    website: "https://www.blueshieldca.com",
    confidence: 0.91,
    states: ["CA"],
    parentNames: [
      normalizeBrandPhrase("California Physicians' Service"),
      "blue shield of california",
    ],
    entityTokens: ["blue shield of california"],
  }),
  rule({
    id: "parent-point32health",
    parentOrg: "Point32Health, Inc.",
    domain: "point32health.org",
    website: "https://www.point32health.org",
    confidence: 0.91,
    national: true,
    parentNames: ["point32health", "point32health inc"],
    entityTokens: ["point32health"],
  }),
  rule({
    id: "parent-caresource",
    parentOrg: "CareSource",
    domain: "caresource.com",
    website: "https://www.caresource.com",
    confidence: 0.91,
    national: true,
    parentNames: ["caresource"],
    entityTokens: ["caresource"],
  }),
  rule({
    id: "parent-premera",
    parentOrg: "Premera Blue Cross",
    domain: "premera.com",
    website: "https://www.premera.com",
    confidence: 0.91,
    states: ["AK", "WA", "OR"],
    parentNames: ["premera blue cross", "premera"],
    entityTokens: ["premera blue cross blue shield", "premera blue cross"],
  }),
  rule({
    id: "parent-scan",
    parentOrg: "SCAN Group",
    domain: "scanhealthplan.com",
    website: "https://www.scanhealthplan.com",
    confidence: 0.91,
    states: ["CA"],
    parentNames: ["scan group", "scan health plan"],
    entityTokens: ["scan health plan"],
  }),
  rule({
    id: "parent-la-care",
    parentOrg: "L.A. Care Health Plan",
    domain: "lacare.org",
    website: "https://www.lacare.org",
    confidence: 0.91,
    states: ["CA"],
    parentNames: [
      normalizeBrandPhrase("Local Initiative Health Authority for LA County"),
      "la care health plan",
    ],
    entityTokens: ["la care health plan"],
  }),
  rule({
    id: "parent-metroplus",
    parentOrg: "MetroPlus Health Plan",
    domain: "metroplus.org",
    website: "https://www.metroplus.org",
    confidence: 0.91,
    states: ["NY"],
    parentNames: [
      normalizeBrandPhrase("New York City Health and Hospitals Corporation"),
      "metroplus health plan",
    ],
    entityTokens: ["metroplus health plan"],
  }),
  rule({
    id: "parent-pacificsource",
    parentOrg: "PacificSource",
    domain: "pacificsource.com",
    website: "https://www.pacificsource.com",
    confidence: 0.91,
    states: ["OR", "ID", "MT"],
    parentNames: ["pacificsource", "pacificsource medicare"],
    entityTokens: ["pacificsource"],
  }),
  rule({
    id: "parent-sentara",
    parentOrg: "Sentara Health Plans",
    domain: "sentarahealthplans.com",
    website: "https://www.sentarahealthplans.com",
    confidence: 0.9,
    states: ["VA"],
    parentNames: ["sentara health plans", "sentara health care"],
    entityTokens: ["sentara health plans"],
  }),
  rule({
    id: "parent-bcbs-ri",
    parentOrg: "Blue Cross & Blue Shield of Rhode Island",
    domain: "bcbsri.com",
    website: "https://www.bcbsri.com",
    confidence: 0.91,
    states: ["RI"],
    entityTokens: ["blue cross blue shield of rhode island", "bcbs of rhode island"],
  }),
  rule({
    id: "parent-bcbs-mn",
    parentOrg: "Blue Cross and Blue Shield of Minnesota",
    domain: "bluecrossmn.com",
    website: "https://www.bluecrossmn.com",
    confidence: 0.91,
    states: ["MN"],
    parentNames: ["blue cross blue shield mn", "blue cross blue shield of minnesota"],
    entityTokens: ["blue cross blue shield of minnesota", "blue cross blue shield mn"],
  }),
];
